# Service pour la base de données Postgres
services:
  postgres:
    image: postgres:16-alpine
    container_name: geodiag_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service pour l'application API Node.js
  api:
    build: .
    container_name: geodiag_api
    restart: always
    env_file:
      - .env
    ports:
      - "4000:4000"
    # S'assure que le service postgres est démarré avant de lancer l'api
    depends_on:
      - postgres
    volumes:
      - .:/app
      # Empêche le dossier node_modules local de masquer celui du conteneur.
      - /app/node_modules

volumes:
  postgres_data: