services:
  postgres:
    image: postgres:17-alpine3.21
    container_name: geodiag_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: