services:
  # Service pour l'application API Node.js
  api:
    build: .
    container_name: geodiag_api
    # Utilise un fichier .env à la racine pour charger les variables d'environnement.
    env_file:
      - .env
    ports:
      # Mappe le port de l'API défini dans le .env (ex: 3000) au même port sur la machine hôte.
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    # S'assure que la base de données et Redis sont démarrés avant l'API.
    depends_on:
      db:
        condition: service_healthy # Assure que la base de données est prête avant de démarrer l'API.
      redis:
        condition: service_healthy # Assure que Redis est prêt avant de démarrer l'API.

    # La commande pour lancer l'application en mode développement avec hot-reloading.
    command: npm start

  # Service pour le worker Node.js
  worker:
    build: .
    container_name: geodiag_worker
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    # S'assure que la base de données et Redis sont démarrés avant le worker.
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

    # La commande pour lancer le worker.
    command: npm run worker

  # Service pour la base de données PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: geodiag_db
    env_file:
      - .env
    ports:
      # Mappe le port de la BDD pour un accès externe (ex: avec un client SQL).
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Service pour le cache Redis
  redis:
    image: redis:latest
    container_name: geodiag_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

# Définit les volumes nommés pour la persistance des données.
volumes:
  postgres_data:
  redis_data:
