services:
  postgres:
    image: postgres:16-alpine  
    container_name: geodiag_db
    restart: always
    environment:
      POSTGRES_USER: user_geodiag      
      POSTGRES_PASSWORD: password_geodiag
      POSTGRES_DB: geodiag_db
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: