name: CI & Deploy

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  # ===============================================
  # ==      JOB 1: TESTER L'APPLICATION          ==
  # ===============================================
  test:
    name: Test Application
    environment: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: geodiag
          POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
          POSTGRES_DB: geodiag_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Apply DB migrations to test database
        # Exécute les migrations sur la BDD de test temporaire
        run: npm run migrate up
        env:
          # Construit l'URL de connexion pour node-pg-migrate
          DATABASE_URL: postgresql://geodiag:${{ secrets.TEST_DB_PASSWORD }}@localhost:5432/geodiag_test

      - name: Run tests
        run: npm test
        env:
          DATABASE_URL: postgresql://geodiag:${{ secrets.TEST_DB_PASSWORD }}@localhost:5432/geodiag_test
          JWT_SECRET: ${{ secrets.TEST_JWT_SECRET }}

  # ===============================================
  # ==     JOB 2: DÉPLOYER EN PRODUCTION         ==
  # ===============================================
  deploy:
    name: Deploy to Production
    needs: test
    if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    environment: Product
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Apply DB migrations to production database
        # Met à jour la base de données de production avant de déployer le code
        run: npm run migrate up
        env:
          PGHOST: ${{ secrets.PROD_DB_HOST }}
          PGPORT: ${{ secrets.PROD_DB_PORT }}
          PGUSER: ${{ secrets.PROD_DB_USER }}
          PGPASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
          PGDATABASE: ${{ secrets.PROD_DB_DATABASE }}
          JWT_SECRET: ${{ secrets.PROD_JWT_SECRET }}
          JWT_EXPIRATION: ${{ secrets.PROD_JWT_EXPIRATION }}
      
      - name: Deploy application to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}